# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(20, 10, 651, 581))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.plot_up = PlotWidget(self.widget)
        self.plot_up.setObjectName("plot_up")
        self.gridLayout.addWidget(self.plot_up, 0, 1, 1, 1)
        self.plot_left = PlotWidget(self.widget)
        self.plot_left.setObjectName("plot_left")
        self.gridLayout.addWidget(self.plot_left, 1, 0, 1, 1)
        self.plot_right = PlotWidget(self.widget)
        self.plot_right.setObjectName("plot_right")
        self.gridLayout.addWidget(self.plot_right, 1, 2, 1, 1)
        self.plot_down = PlotWidget(self.widget)
        self.plot_down.setObjectName("plot_down")
        self.gridLayout.addWidget(self.plot_down, 2, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
from pyqtgraph import PlotWidget
